version: '3'

services:
  database:
    image: mariadb:latest
    container_name: hackathon_mariadb
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 33065:3306

  php-fpm:
    build:
      context: ./docker/php-fpm/
      args:
        - XDEBUG_ENABLE=${XDEBUG_ENABLE}
        - XDEBUG_REMOTE_PORT=${XDEBUG_REMOTE_PORT}
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
    container_name: hackathon_php-fpm
    environment:
      APP_ENV: ${APP_ENV}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database

  nginx:
    build:
      context: ./docker/nginx
    container_name: hackathon_nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/sites-available/:/etc/nginx/sites-available/
      - ./src:/var/www/html
    ports:
      - 820:80 #backend
      - 8201:81 #frontend
      - 8333:83 #phpmyadmin
    depends_on:
      - php-fpm
